##==> Fill this backend service manifest
##==> Fill this backend service manifest
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: LoadBalancer