##==> Fill this backend deployment manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: monalisasdi/monalisabackend:latest
        ports:
          - containerPort: 3000
        env:
          - name: NODE_ENV
            value: DEV